version: 2.1

defaults: &defaults
    working_directory: ~/project
    docker:
        - image: circleci/node:12.22.4

orbs:
    codecov: codecov/codecov@1.1.6

jobs:
    checkout:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: npm ci
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - .

    commitlint:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/project
            - run:
                  name: Lint relevant commit messages
                  command: npm run commitlint:ci

    lint:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/project
            - run:
                  name: Lint TypeScript code
                  command: npm run lint:ci
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - reports/eslint

    lintejs:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/project
            - run:
                  name: Lint ejs template files
                  command: npm run lint:ejs

    build:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/project
            - run:
                  name: Build TypeScript code
                  command: npm run build
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - .
            - store_test_results:
                  path: reports
            - store_artifacts:
                  path: reports

    test:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/project
            - run:
                  name: Test TypeScript code
                  command: npm run test:ci
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - coverage
                      - reports/jest

    codecov:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/project
            - codecov/upload:
                  file: ./coverage/lcov.info

    release:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/project
            - run: npx semantic-release

workflows:
    build:
        jobs:
            - checkout
            - lint:
                  requires:
                      - checkout
            - lintejs:
                  requires:
                      - checkout
            - commitlint:
                  requires:
                      - checkout
            - build:
                  requires:
                      - lint
                      - commitlint
            - test:
                  requires:
                      - build
            - codecov:
                  requires:
                      - test
            - release:
                  requires:
                      - build
                      - test
                  filters:
                      branches:
                          only: master
