stages:
    - test
    - build

lint:
    image: hadolint/hadolint:v1.17.5-2-g44d0caa-debian
    stage: test
    script:
        - hadolint Dockerfile

build:
    image: docker:20.10.24
    stage: build
    services:
        - docker:20.10.24-dind
    variables:
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: '/certs'
    script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
        - docker push "$CI_REGISTRY_IMAGE:latest"
