version: 2.1

orbs:
    docker: circleci/docker@0.5.20

jobs:
    checkout:
        docker:
            - image: circleci/node:12.15.0
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run:
                  name: Install v1-dependencies
                  command: npm ci
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - persist_to_workspace:
                  root: $CIRCLE_WORKING_DIRECTORY
                  paths:
                      - .

    build:
        docker:
            - image: circlecI/node:12.15.0
        steps:
            - attach_workspace:
                  at: $CIRCLE_WORKING_DIRECTORY
            - setup_remote_docker:
                  docker_layer_caching: true
            - run:
                  name: build docker image
                  command: docker build -t <%= authorName %>/<%= moduleName %> .
            - run:
                  name: persist docker image
                  command: docker save -o image.tar <%= authorName %>/<%= moduleName %>
            - persist_to_workspace:
                  root: $CIRCLE_WORKING_DIRECTORY
                  paths:
                      - image.tar

    release:
        docker:
            - image: circlecI/node:12.15.0
        steps:
            - attach_workspace:
                  at: $CIRCLE_WORKING_DIRECTORY
            - setup_remote_docker:
                  docker_layer_caching: true
            - run:
                  name: load docker image
                  command: docker load -i image.tar
            - run:
                  name: release docker image
                  command: npx semantic-release

workflows:
    build:
        jobs:
            - checkout
            - docker/hadolint:
                  requires:
                      - checkout
                  dockerfile: Dockerfile
                  ignore-rules: 'DL4005,DL3008'
            - build:
                  requires:
                      - docker/hadolint
            - release:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master
